name: Release to GitHub Marketplace

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Containerize
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: check version change
        id: version
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: verify version change
        if: steps.version.outputs.changed == 'false'
        run: 'echo "VERSION CHANGE NOT DETECTED" && exit 1'

      - uses: actions/setup-node@v4

      - name: build
        run: npm ci && npm run build

      - name: verify `dist` is up-to-date
        run: |
          if ! git diff --ignore-space-at-eol --exit-code --quiet dist/index.mjs; then
            echo "Detected out-of-date build. See status below:"
            git diff
            exit 1
          fi

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.version.outputs.version }}
          files: |
            *